# Generated by Django 5.2.14 on 2026-05-30 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('customer_type', models.CharField(choices=[('retail', 'مشتری عادی'), ('wholesale', 'بنک\u200cدار'), ('credit', 'مشتری چکی'), ('vip', 'مشتری VIP')], default='retail', max_length=20, verbose_name='نوع مشتری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('suspended', 'معلق')], default='pending', max_length=20, verbose_name='وضعیت حساب')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت/فروشگاه')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('holoo_erp_code', models.CharField(blank=True, help_text='شناسه یکتای این مشتری در نرم\u200cافزار هلو', max_length=255, null=True, unique=True, verbose_name='شناسه هلو (ErpCode)')),
                ('is_imported_from_holoo', models.BooleanField(default=False, verbose_name='ایمپورت شده از هلو')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
