# Generated by Django 5.2.14 on 2026-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_imported_from_holoo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='holoo_erp_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه هلو (ErpCode)'),
        ),
    ]
