# Generated by Django 5.2.14 on 2026-05-30 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode_rename_phone_number_customuser_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='شماره شبا (IR)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customer_type',
            field=models.CharField(choices=[('unknown', 'نامشخص / در انتظار'), ('retail', 'مشتری عادی'), ('wholesale', 'بنک\u200cدار'), ('credit', 'مشتری چکی'), ('vip', 'مشتری VIP')], default='unknown', max_length=20, verbose_name='نوع مشتری'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی (تومان)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف\u200cهای پول',
            },
        ),
    ]
