# Generated by Django 5.2.14 on 2026-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode_user_alter_bankaccount_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='سقف اعتبار چکی (تومان)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='holoo_customer_code',
            field=models.CharField(blank=True, help_text='کد عددی مشتری در هلو (ReturnParam1)', max_length=50, null=True, unique=True, verbose_name='کد طرف حساب هلو (Code)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='لیست سیاه هلو'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customer_type',
            field=models.CharField(choices=[('unknown', 'نامشخص / در انتظار تعیین'), ('retail', 'مشتری عادی'), ('wholesale', 'بنک\u200cدار'), ('credit', 'مشتری چکی'), ('vip', 'مشتری VIP')], default='unknown', max_length=20, verbose_name='نوع مشتری (تجاری)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی / شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی ادمین'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('suspended', 'معلق')], default='pending', max_length=20, verbose_name='وضعیت حساب'),
        ),
    ]
