# Generated by Django 5.2.14 on 2026-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='holoo_customer_code',
            field=models.CharField(blank=True, db_index=True, help_text='کد عددی مشتری در هلو - ReturnParam1', max_length=50, null=True, verbose_name='کد طرف حساب هلو (Code)'),
        ),
    ]
