# Generated by Django 5.2.14 on 2026-05-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس (Slug)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس (Slug)')),
                ('is_holoo_main_group', models.BooleanField(default=False, verbose_name='آیا گروه اصلی هلو است؟')),
                ('holoo_erp_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه هلو (ErpCode)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته/بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='آدرس (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات معرفی محصول')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح کوتاه / خلاصه')),
                ('holoo_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='کد کالا هلو (Code)')),
                ('holoo_erp_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه هلو (ErpCode)')),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد اندازه\u200cگیری (مثلا: عدد)')),
                ('unit_erp_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه واحد هلو')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی کل (Few)')),
                ('stock_carton', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی کارتن (FewKarton)')),
                ('count_in_carton', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد در کارتن')),
                ('count_in_basteh', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد در بسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('buy_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت خرید (مبنای سود)')),
                ('sellprice', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 1 (عادی)')),
                ('sellprice2', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 2 (بنک\u200cدار)')),
                ('sellprice3', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 3 (چکی)')),
                ('sellprice4', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 4 (VIP)')),
                ('sellprice5', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 5')),
                ('sellprice6', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 6')),
                ('sellprice7', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 7')),
                ('sellprice8', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 8')),
                ('sellprice9', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 9')),
                ('sellprice10', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 10')),
                ('sellprice_karton', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش کارتن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر در سایت')),
                ('last_holoo_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی با هلو')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی فرعی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (سئو)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('is_notified', models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی شده؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاع\u200cرسانی موجودی',
                'verbose_name_plural': 'درخواست\u200cهای اطلاع\u200cرسانی موجودی',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'لیست علاقه\u200cمندی\u200cها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
